# Generated by Django 5.2.12 on 2026-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_created_at_cartitem_added_at_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
