# Generated by Django 5.2.12 on 2026-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_created_at_product_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
